### ISSUE TITLE
setup.py PEP8 format errors

### ISSUE THREAD

**Issue by theaverageguy** [coala-analyzer/coala-bears#149]
![m](https://cloud.githubusercontent.com/assets/9817962/13492619/2827f9ac-e15f-11e5-9b84-e60a488fd12f.png)

difficulty/beginner

**Comment by sils1297** [comment]
sorry what is this about, could you be more concrete? Why doesn't coala detect those issues?

**Comment by AbdealiJK** [comment]
Right, how are you running pep8 ?  Arent we already checking pep8 for every PR ?

**Comment by theaverageguy** [comment]
I was testing pep8 and I happened to be in my local directory for coala-bears. I tested pep8 --first setup.py and I got these two format errors. 
The file has a couple of errors regarding proper spacing and printing(as mentioned). Other files like those in css folder don't have such issues. It should be consistent and can be used as a beginner issue.

**Comment by theaverageguy** [comment]
![m](https://cloud.githubusercontent.com/assets/9817962/13493025/6c5980d0-e161-11e5-9732-a61ca5f4f263.png)

**Comment by AbdealiJK** [comment]
So, I do not think this is an issue.
We;re using 80 char instead of79 char everywhere in our code (and our PEP8Bear is configured to use that)
Regarding the module level import, I am guessing `autopep8` which is what we use instead of `pep8` doesnt check for them. We use `PyImportSortBear` instead (although its not there in circleci at the moment - we have an issue for this already)

So, I'm closing this, as we already run PEP8Bear using coala, and it is in accordance to our style spec
