### ISSUE TITLE
InvalidLinkBear: Implement timeout setting and raise default timeout to 2secs

### ISSUE THREAD

**Issue by jarifibrahim** [coala-analyzer/coala-bears#240]
The `InvalidLinkBear` has a timeout of 1 sec which causes a number of links to fail on executing `coala invalidlink`. The timeout period should be atleast 5 sec.

**Comment by sils1297** [comment]
@SanketDG do you agree? Then this is newcoer.

**Comment by Makman2** [comment]
coala-bears doesn't have an `invalidlink` section, this issue should be migrated to coala^^

**Comment by sils1297** [comment]
@Makman2 the bear needs changing, not the coafile

**Comment by Makman2** [comment]
at least `coala invalidlink` does not apply here. Anyway: Don't we have already an issue for using a setting for the timeout? (searching...)

**Comment by Makman2** [comment]
No can't find it any more

**Comment by Makman2** [comment]
@jarifibrahim the better approach here is imo to supply a setting to the bear for the timeout, so you can manually adjust it. We had a discussion about the timeout and agreed on 2secs (though it's only 1 now...), changing it doesn't solve the backgound issue (there could be people that need 10secs due to an even worse internet connection).
@sils1297 do you agree changing this issue to "InvalidLinkBear - Implement timeout setting"?

**Comment by sils1297** [comment]
yeah implement a setting and probably take 2 for default?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-14 20:05 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by SanketDG** [comment]
^ :+1:
