### ISSUE TITLE
JSHintBear isn't usable by default anymore

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#270]
```
client/controllers/logout.js
|   0| ••});
|    | [NORMAL] JSHintBear:
|    | ES5 option is now set per default
```

I think this is related to the changes from @sam09

**Comment by sam09** [comment]
The default argument for ``esversion``  in  ``bears/js/JSHintBear.py`` is set to 5. I think we need to set it to 3. IMHO is could be a newcomer issue.

**Comment by sils1297** [comment]
Can you describe a bit more why this is needed and how it fixes the issue, what esversion is anyway for this to be newcomer suitable?

**Comment by AbdealiJK** [comment]
basically ES is ECMAScript (something like the parent of JS - like there's ANSI-C, C+11 etc norms and various implementations of C compilers like gcc, mingw, etc.). ES's latest version is 5 and most codes do not follow ES5 yet.
@sam09 says the default version sohuld be 3 (Im guessing because that's the most popular one ?)

The reason it's newcomer is because you need to change the version somewhere.

Note though:
There are 2 args for this. `es3` which is False by default and `es_version` which is 5 by default.
I have no clue which needs to be changed nor why there are two of these ... @sam09 could you help in identifying this ?

**Comment by sils1297** [comment]
I think we rather want an es version argument that defaults to three and set es3 implicitly?

**Comment by AbdealiJK** [comment]
Right. That is assuming it is a redundant arg ... maybe there is some
meaning to why they have 2 things for that.
Needs investigation IMO

**Comment by sam09** [comment]
I just found out that ``es3 `` is an option that has been deprecated and will be removed in the next major release of JSHint. So i guess we should remove that.

**Comment by AbdealiJK** [comment]
Seems like the default version is 5 now.
http://stackoverflow.com/questions/15642903/complete-list-of-default-values-for-jshint-options
https://github.com/jshint/jshint/blob/master/examples/.jshintrc#L45

This is expected behaviour umo

**Comment by AbdealiJK** [comment]
It seems like the thing you got is not even a result ... it has line set to 0.
I think jsint is giving a log message "es version is 5 by default" and that's being converted to a Result wrongly

**Comment by sils1297** [comment]
exactly

**Comment by sam09** [comment]
Okay... But the ``es3`` attribute should still be removed cause it is deprecated... But maybe that should be a different issue

**Comment by sils1297** [comment]
related to https://github.com/coala-analyzer/coala-bears/issues/740 we should remove the deprecated settings and deprecate them as well. CC @AbdealiJK

**Comment by AbdealiJK** [comment]
Note that this issue should have actually been closed along with https://github.com/coala-analyzer/coala-bears/issues/338
I'm not sure why I had created a different issue for it at that time ...

Anyway. I found `globalstrict` has been deprecated and have added a commit to deprecate that in coala too. Went through the other args, and everything else seems fine in JSHint.
