### ISSUE TITLE
CSecurityBear: Change ''-> `` 

### ISSUE THREAD

**Issue by Asnelchristian** [coala-analyzer/coala-bears#587]
[line](https://github.com/coala-analyzer/coala-bears/blob/master/bears/c_languages/CSecurityBear.py#L35)

**Comment by OndraSky** [comment]
On it

**Comment by underyx** [comment]
@Asnelchristian FYI you can get a permalink for a line from GitHub by pressing the `y` keyboard shortcut. This issue was a bit difficult to fix, cause the file has changed since you noted down the line number, and now it's pointing to an unrelated one. if you change your link to

https://github.com/coala-analyzer/coala-bears/blob/a6597e8b0889faab10c8483cb73c30d315eab636/bears/c_languages/CSecurityBear.py

which specified the revision, it'll be way easier to find.
