### ISSUE TITLE
[Bear Proposal] PVSBear

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala-bears#652]
http://www.viva64.com/en/pvs-studio/

**Comment by Asnelchristian** [comment]
i am on it :)

**Comment by Makman2** [comment]
it's not free btw^^

**Comment by sims1253** [comment]
oh :D
then maybe close this?

**Comment by Asnelchristian** [comment]
okay :) :sweat:  i am closing it  :(

**Comment by sils1297** [comment]
Could still be nice, legally it's ok to have non free software in another
process. Well want to think about a general policy. I think just not
shipping them by default and prioritizing free software might be neat.

On 4 Aug 2016 4:17 p.m., "Asnelchristian" <notifications@github.com> wrote:

Closed #652 <https://github.com/coala-analyzer/coala-bears/issues/652>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/coala-analyzer/coala-bears/issues/652#event-745435279>,
or mute the thread

**Comment by Makman2** [comment]
that's what I think too, as an free open-source project we should support free tools^^

**Comment by Makman2** [comment]
especially testing could get a problem^^
