### ISSUE TITLE
IDEA: Options enabled by comment

### ISSUE THREAD

**Issue by oreqizer** [coala-analyzer/coala-bears#781]
For example like `eslint`:

```javascript
case VIEWS.TRANSACTIONS: // eslint-enable indent
```

**Comment by AbdealiJK** [comment]
So, this would be like enabling a bear on only a specific section based on a comment in coala. The opposite of `// Ignore <bearname>`

It may be a bit difficult to implement because we rely on the config file to figure out which bears to load, and now we'd have to parse the file to figure out which bears to load itself.

CC @Udayan12167 as it'd probably be easier to be planned from the start in the next-gen-bear design

PS: Moving it to coala, as it's coala core specific

**Comment by AbdealiJK** [comment]
This issue was moved to coala-analyzer/coala#2714
